API Contract for Message_ID:
GET Method:
openapi: 3.0.0
info:
  title: KnowledgeHub API
  version: 1.0.0
paths:
  /KnowledgeHub/Messages/{Message_ID}:
    get:
      summary: Retrieve data by ID
      parameters:
        - in: path
          name: Message_ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    properties:
                      Message_ID:
                        type: integer
                        description: The ID of the message
                      Technology_Type:  
                        type: string
                        description: The technology type of the message
                      Exception_Type:
                        type: string
                        description: The exception type of the message
                      Exception_Title:
                        type: string
                        description: The exception title of the message
                      Descpription:
                        type: string
                        description: The description of the message
-----------------------------------------------------------------------------------------------------------------------------
API Contract for Exception Type:
GET Method:
openapi: 3.0.0
info:
  title: KnowledgeHub API
  version: 1.0.0
paths:
  /KnowledgeHub/Expection_Type:
    get:
      summary: Retrieve exception type details
      parameters:
        - in: query
          name: messgae_id
          required: true
          schema:
            type: integer
            description: The ID of the message
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                      Message_ID:
                        type: integer
                        description: The ID of the message
                      Technology_Type:  
                        type: string
                        description: The technology type of the message
                      Exception_Type:
                        type: string
                        description: The exception type of the message
                      Exception_Title:
                        type: string
                        description: The exception title of the message
                      Description:
                        type: string
                        description: The description of the message
---------------------------------------------------------------------------------------------------------------------------------
POST Method:
openapi: 3.0.0
info:
  title: KnowledgeHub API
  version: 1.0.0
paths:
  /KnowledgeHub/Exception_Type:
    get:
      summary: Retrieve exception type details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  exception_type:
                    type: string
    post:
      summary: Create a new exception type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                exception_type:
                  type: string
            example: 
              exception_type: "NewExceptionType"
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
-------------------------------------------------------------------------------------------------------------------------------------
API Contract for Technology Type:
GET Method:
openapi: 3.0.0
info:
  title: KnowledgeHub API
  version: 1.0.0
paths:
  /KnowledgeHub/Technology_Type:
    get:
      summary: Retrieve technology type details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  technology_type:
                    type: string
                    properties:
                      Message_ID:
                        type: integer
                        description: The ID of the message
                      Technology_Type:
                        type: string
                        description: The technology type of the message
                      Description:
                        type: string
                        description: The description of the message
                      Exception_Title:
                        type: string
                        description: The exception title of the message
                      Description:
                        type: string
                        description: The description of the message
-------------------------------------------------------------------------------------------------------------------------------------
POST Method:
openapi: 3.0.0
info:
  title: KnowledgeHub API
  version: 1.0.0
paths:
  /KnowledgeHub/Technology_Type:
    get:
      summary: Retrieve technology type details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  technology_type:
                    type: string
    post:
      summary: Create a new technology type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                technology_type:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request         