openapi: 3.0.0
info:
  title: Knowledge Hub API
  description: API documentation for retrieving data from the Knowledge Hub.
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production server
paths:
  /KnowledgeHub/GetData_Using_ID/{Message_ID}:
    get:
      summary: Retrieve Data from Knowledge Hub by Message ID
      description: |
        Retrieves data from the Knowledge Hub based on the provided Message ID.
      parameters:
        - in: path
          name: Message_ID
          required: true
          description: The unique identifier of the message.
          schema:
            type: integer
      responses:
        '200':
          description: A successful response containing the requested data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Message_ID:
                    type: integer
                    description: The unique identifier of the message.
                  Technology_Type:
                    type: string
                    description: The type of technology associated with the message.
                  Exception_Type:
                    type: string
                    description: The type of exception.
                  Exception_Title:
                    type: string
                    description: The title of the exception.
                  Description:
                    type: string
                    description: A description of the exception.
        '404':
          description: Not found. The requested resource does not exist.
        '500':
          description: Internal server error. An unexpected error occurred on the server.
      security:
        - apiKey: []


API Example:
URL:
http://127.0.0.1:8000/docs#/default/GetData_KnowledgeHub_GetData_Using_ID__Message_ID__get

Request Body
{
  http://127.0.0.1:8000/KnowledgeHub/GetData_Using_ID/1
}
Response Body
{[
  {
    "Message_ID": 1,
    "Technology_Type": "JS",
    "Exception_Type": "Error",
    "Exception_Title": "Permission denied to access property \"x\"",
    "Description": "The JavaScript exception \"Permission denied to access property\" occurs when there was an attempt to access an object for which you have no permission."
  }
]}
